#!/usr/bin/env Rscript
#
# Generate frozen lostruct reference outputs for pg_gpu parity tests.
#
# This script is developer-local only. It is NOT run by CI or pytest.
# Run manually when upstream lostruct changes or when the reference input
# is updated; commit the resulting *.npz files alongside this script.
#
# Requirements (install into your personal R library, NOT the pg_gpu env):
#
#   install.packages(c("data.table", "devtools", "RSpectra", "jsonlite"))
#   devtools::install_github("petrelharp/local_pca/lostruct")
#
# Usage (from repo root):
#
#   Rscript tests/data/generate_lostruct_reference.R
#
# Reads: tests/data/generate_lostruct_reference_input.json
#   (committed; generated by a companion Python script — see
#    tests/data/generate_lostruct_reference_input.py)
#
# Writes:
#   tests/data/lostruct_reference_eigen.json
#   tests/data/lostruct_reference_pcdist.json
#   tests/data/lostruct_reference_jackknife.json
#   tests/data/lostruct_reference_corners.json
#
# JSON is used instead of .npz to avoid a C/Python IPC dependency in R; the
# Python parity tests load the JSON arrays via numpy. Values use IEEE double
# precision (15-16 decimal digits) so jsonlite round-trips them losslessly.

suppressPackageStartupMessages({
    library(lostruct)
    library(jsonlite)
})

here <- function(...) file.path("tests", "data", ...)

# -- Load the input haplotype matrix (samples x variants, 0/1) ---------------
input_path <- here("generate_lostruct_reference_input.json")
if (!file.exists(input_path)) {
    stop("Missing ", input_path, ". Generate it with ",
         "tests/data/generate_lostruct_reference_input.py first.")
}
input <- fromJSON(input_path)
hap <- as.matrix(input$hap)   # samples x variants (rows = samples)
positions <- as.numeric(input$positions)
window_size <- as.integer(input$window_size)  # SNP-count window
k <- as.integer(input$k)
n_blocks <- as.integer(input$n_blocks)
prop <- as.numeric(input$prop)
k_corners <- as.integer(input$k_corners)
normalize_L1 <- "L1"
normalize_L2 <- "L2"

n_samples <- nrow(hap)
n_variants <- ncol(hap)

cat(sprintf("n_samples=%d  n_variants=%d  win=%d  k=%d\n",
            n_samples, n_variants, window_size, k))

# lostruct expects variants as rows, samples as columns.
variant_major <- t(hap)  # (n_variants, n_samples)

# -- Per-window eigen decomposition ------------------------------------------
eigs <- eigen_windows(variant_major, k = k, win = window_size)
# eigs has shape (n_windows, 1 + k + k*n_samples)
n_windows <- nrow(eigs)
sumsq <- eigs[, 1]
eigvals <- eigs[, 2:(1 + k), drop = FALSE]          # (n_windows, k)
eigvecs_flat <- eigs[, -(1:(1 + k)), drop = FALSE]  # (n_windows, k * n_samples)
# R flattens column-major (as.vector(U) with U shape (n_samples, k));
# that equals C-order flatten of (k, n_samples). Store as list-of-lists so
# the Python side can reshape((n_windows, k, n_samples)).
eigvecs <- array(0, dim = c(n_windows, k, n_samples))
for (w in 1:n_windows) {
    U <- matrix(eigvecs_flat[w, ], ncol = k)    # (n_samples, k)
    eigvecs[w, , ] <- t(U)                      # (k, n_samples)
}
write_json(list(
    sumsq = sumsq,
    eigvals = eigvals,
    eigvecs = eigvecs,
    n_windows = n_windows,
    n_samples = n_samples,
    k = k
), here("lostruct_reference_eigen.json"), digits = 17, auto_unbox = TRUE)

# -- pc_dist under L1, L2, none ----------------------------------------------
dist_L1 <- pc_dist(eigs, npc = k, normalize = "L1")
dist_L2 <- pc_dist(eigs, npc = k, normalize = "L2")
# 'none' isn't directly supported by pc_dist; we approximate by using raw
# eigenvalues without normalization. lostruct's pc_dist always normalizes,
# so skip 'none' and document the divergence.
write_json(list(
    dist_L1 = dist_L1,
    dist_L2 = dist_L2,
    n_windows = n_windows
), here("lostruct_reference_pcdist.json"), digits = 17, auto_unbox = TRUE)

# -- Jackknife SE per window (per-PC, averaged over samples) -----------------
# Ported from dpgp/DPGP_jackknife_var.R to the whole window set.
jackknife_per_window <- function(w_idx, variant_major, win, k, n_blocks) {
    var_start <- (w_idx - 1) * win + 1
    var_end <- w_idx * win
    Xv <- variant_major[var_start:var_end, , drop = FALSE]  # (win, n_samples)
    step <- floor(win / n_blocks)
    se_per_pc <- rep(NA_real_, k)
    for (pc in 1:k) {
        reps <- matrix(NA_real_, nrow = n_blocks, ncol = ncol(Xv))
        for (b in 1:n_blocks) {
            idx <- ((b - 1) * step + 1):(b * step)
            chunk <- Xv[-idx, , drop = FALSE]
            M <- rowMeans(chunk, na.rm = TRUE)
            chunk_c <- sweep(chunk, 1, M, "-")
            covm <- cov(chunk_c, use = "pairwise")
            if (any(is.na(covm))) { reps[b, ] <- NA; next }
            eig <- eigen(covm)
            reps[b, ] <- eig$vectors[, pc]
        }
        # Sign align to first replicate
        base <- reps[1, ]
        for (b in 1:nrow(reps)) {
            if (sum((base - reps[b, ])^2) > sum((base + reps[b, ])^2)) {
                reps[b, ] <- -reps[b, ]
            }
        }
        m <- colMeans(reps)
        var_per_sample <- ((n_blocks - 1) / n_blocks) *
            colSums(sweep(reps, 2, m, "-")^2)
        se_per_pc[pc] <- mean(sqrt(var_per_sample))
    }
    se_per_pc
}

jk_se <- t(sapply(1:n_windows, jackknife_per_window,
                  variant_major = variant_major, win = window_size,
                  k = k, n_blocks = n_blocks))
write_json(list(
    se_per_pc = jk_se,
    n_blocks = n_blocks
), here("lostruct_reference_jackknife.json"), digits = 17, auto_unbox = TRUE)

# -- MDS + corners -----------------------------------------------------------
mds <- cmdscale(dist_L1, k = 2)
if (is.null(dim(mds))) mds <- matrix(mds, ncol = 2)
corner_idx <- corners(mds, prop = prop, k = k_corners)
# corners returns 1-based indices; convert to 0-based for Python parity.
corner_idx <- corner_idx - 1L
write_json(list(
    mds_coords = mds,
    corner_indices = corner_idx,
    prop = prop,
    k_corners = k_corners
), here("lostruct_reference_corners.json"), digits = 17, auto_unbox = TRUE)

cat("Wrote reference outputs to tests/data/lostruct_reference_*.json\n")
